# Generated by Django 2.0.4 on 2018-04-07 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textual_emotional', models.CharField(max_length=1000)),
                ('textual_sentimental', models.CharField(max_length=1000)),
                ('facial_emotional', models.CharField(max_length=1000)),
                ('textual_conversation', models.CharField(max_length=5000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
    ]
