# Generated by Django 2.0.4 on 2018-04-07 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
